version: '3.8'

services:
  # Frontend Next.js app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules  # Prevents node_modules from being overwritten
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - server
    # Hot reload for development
    command: npm run dev

  # Backend API
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules  # Same as above - don't overwrite modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret_replace_in_prod}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    # Using nodemon for auto-reload
    command: npm run dev

  # Redis for caching and rate limiting
  # TODO: Add persistence if we end up needing it
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 